### ISSUE TITLE
Floats as keys inexact (again?)

### ISSUE THREAD

**Issue by grahamas** [Tokazama/AxisIndices.jl#35]
Possibly a regression to whatever you fixed in #13? 

```
julia> A = AxisArray(1:6, 0.5:0.1:1.0)
6-element AxisArray{Int64,1}
 • dim_1 - 0.5:0.1:1.0
           
  0.5   1  
  0.6   2  
  0.7   3  
  0.8   4  
  0.9   5  
  1.0   6  

julia> A[0.5]
1

julia> A[0.6]
ERROR: BoundsError: attempt to access 6-element typename(Axis)(0.5:0.1:1.0 => Base.OneTo(6)) at index [0.6]
Stacktrace:
 [1] to_index
   @ ~/.julia/dev/AxisIndices/src/Interface/to_index.jl:32 [inlined]
 [2] to_index
   @ ~/.julia/dev/AxisIndices/src/Interface/to_index.jl:18 [inlined]
 [3] to_indices
   @ ~/.julia/dev/AxisIndices/src/Interface/to_indices.jl:24 [inlined]
 [4] getindex(A::AxisVector{Int64,UnitRange{Int64},Axis{Float64,Int64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Base.OneTo{Int64}}}, args::Float64)
   @ AxisIndices.Arrays ~/.julia/dev/AxisIndices/src/Arrays/AbstractAxisArray.jl:130
 [5] top-level scope
   @ REPL[59]:1

To edit a specific method, type the corresponding number into the REPL and press Ctrl+Q
```
then testing the `find_firsteq` from StaticRanges used on `to_index.jl:31`:
```
julia> AxisIndices.find_firsteq(0.5, keys(axes(A)[1]))
1

julia> AxisIndices.find_firsteq(0.6, keys(axes(A)[1]))

julia> 
```
confirms that 0.6 is not found to be equal to any key in the Axis, even though:
```
julia> keys(axes(A)[1]) .== 0.6
6-element BitVector:
 0
 1
 0
 0
 0
 0
```

**Comment by grahamas** [comment]
uhhhh
```
julia> A = AxisArray(1:6, 0.5:0.1:1.0)
6-element AxisArray{Int64,1}
 • dim_1 - 0.5:0.1:1.0
           
  0.5   1  
  0.6   2  
  0.7   3  
  0.8   4  
  0.9   5  
  1.0   6  

julia> A[0.5]
1

julia> A[0.6]
1

julia> A[0.7]
2

julia> A[0.8]
4

julia> A[0.9]
5

julia> A[1.0]
6
```
(pinned StaticRanges@0.7.0 as I move backwards to pinpoint the error, but the commit log doesn't indicate this was fixed)

**Comment by grahamas** [comment]
There might be some underlying dependency that's not being affected by my reversions.  I'm back to AxisIndices@0.4.0 and StaticRanges@0.6.6 and I'm still finding

```
julia> using AxisIndices; A = AxisArray(1:6, 0.5:0.1:1.0); A[[0.5, 0.6, 0.7]]
[ Info: Precompiling AxisIndices [f52c9ee2-1b1c-4fd8-8546-6350938c7f11]
3-element AxisArray{Int64,1}
 • dim_1 - [0.5, 0.6, 0.7]
           
  0.5   1  
  0.6   1  
  0.7   2  
```

**Comment by Tokazama** [comment]
I never made approximate indexing the default. I just made i so that you could use `isapprox(index, atol=atol)`. `isapprox` is slower than `==`, so it's not straightforward that using approximate indexing would always be the best.

**Comment by grahamas** [comment]
Ahhhh sorry I misunderstood.  Of course, this makes sense.

You might consider revising some of the documentation, though. I haven't seen anything *wrong*, but it doesn't reinforce the fact that indexing by float will be error-prone. For example, the Axis documentation includes some indexing by equality to a float. If you change `time1` to be `time1 = Axis((1.5:.1:10)s)`, then `time1[1.7s]` errors, as does `time1[==(1.7s)]`, both of which are nearly the same as the current examples using `1.5s`.
