### ISSUE TITLE
Needs testing

### ISSUE THREAD

**Issue by grahamas** [Tokazama/AxisIndices.jl#38]
The repo needs basic testing to avoid some of the regressions that have popped up. I'm happy to set up most of this, but I think the Travis integration needs to be set up by the maintainer.

**Comment by grahamas** [comment]
Wow, I'm missing a lot today.  Obviously there's testing.  I'll add some relevant tests in my PR.

**Comment by Tokazama** [comment]
For the record, I'd be happy to have more tests for things that aren't explicitly tested yet.  However, most documented features are tested at this point.
