### ISSUE TITLE
AxisArrays print their entire contents?

### ISSUE THREAD

**Issue by yurivish** [Tokazama/AxisIndices.jl#53]
This is causing a hang in Pluto notebooks for large matrices. 

A simple example at the REPL, AxisIndices version 0.6.4:

```
julia> using AxisIndices
julia> AxisArray(rand(100,100), 1:100, 1:100) # prints the entire 100x100 array
```

**Comment by Tokazama** [comment]
Thanks for bringing this to my attention. I haven't specifically tested this on Pluto, but it is fixed in terminal REPL. Feel free to create another issue if there's still a problem.

**Comment by yurivish** [comment]
Thanks! I just checked and this issue is fixed in Pluto too.
