### ISSUE TITLE
Indexing with custom type's name

### ISSUE THREAD

**Issue by kescobo** [Tokazama/AxisIndices.jl#59]
This may not be a pattern that makes sense to support, but I wanted to write this up to see if there's a way to implement it without sacrificing (too much) performance. I basically want to implement a table type where the column names are one type, and the row names are a different type. But I think it's possible to just consider the 1D case. So the easy version that I figured out is:

```
struct Foo
    name::String
end

struct Wrapper
    aa::AxisArray
end

Base.getindex(w::Wrapper, ind::AbstractString) = w.aa[Foo(ind)]
```

Then I can do

```
julia> foos = [Foo("foo1"), Foo("foo2")];

julia> vals = rand(2);

julia> aa = Warpper(AxisArray(vals, foos));

julia> aa["foo1"]
0.04643928287695687
```

But I'd really like `Foo` to be a type with multiple fields, and for the indexing to work just on the name field, regardless of what's  in  the other ones. Eg.

```
struct Bar
    name::String
    somethingelse
end

bars = [Bar("bar1", :asymbol), Bar("bar2", missing)]
aa2 = Wrapper(AxisArray(vals, bars))

aa2["bar2"] # how do I get this to work?
```

One thought I had is that I could store an additional vector in `Wrapper` that contains just the names and index on that, but then if I take subsets, I don't want to have to deal with updating the subsets and their indices. But there may be a way to do this that's not obvious to me.

I read in the docs that things like `findall` are optimized with axes, but would it still be performant to make `getindex` rely on calling `findfirst` or something on the axis names?

**Comment by kescobo** [comment]
Hmm - it seems I can just define `Base.:(==)` for my `Bar` type to only rely on the `name` field, and it seems to work great.

```
Base.:(==)(b1::Bar, b2::Bar) = b1.name == b2.name
Bar(s::String) = Bar(s, missing)
```

Then

```
julia> aa2["bar1"]
0.04643928287695687

julia> aa2["bar2"]
0.07273069283718936
```

Sorry for the noise!

**Comment by Tokazama** [comment]
You can get pretty creative with what you index by using custom types, as you've already figured out. I'll just comment on this:

>This may not be a pattern that makes sense to support

Feel free to bring up issues with any pattern here you need help supporting. Even if it's something that shouldn't be explicitly supported here maybe there's a way to make AxisIndices more generic so it's easy to implement.

**Comment by kescobo** [comment]
Will do, thanks! It might be nice to be able to do this without overloading `==`, but that works just fine for my use-case, so there's no urgency on my end.
